services:
  minio:
    image: minio/minio:RELEASE.2022-11-08T05-27-07Z
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"

  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - "2182:2181"

  course-kafka:
    image: wurstmeister/kafka:2.13-2.8.1
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://course-kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper

  kafdrop:
    image: obsidiandynamics/kafdrop:latest
    ports:
      - "9003:9000"
    environment:
      KAFKA_BROKERCONNECT: course-kafka:9092
      JVM_OPTS: "-Xms1g -Xmx2g"
      KAFKA_FETCH_TIMEOUT_MS: 120000  # Increase timeout to 120 seconds
    depends_on:
      - course-kafka

  dev_env:
    image: ofrir119/developer_env:spark340_ssh
    ports:
      - "22022:22"
      - "8888:8888"
      - "4040:4040"
      - "4041:4041"
      - "4042:4042"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.2
    ports:
      - "9200:9200"
    environment:
      discovery.type: single-node

  kibana:
    image: docker.elastic.co/kibana/kibana:7.13.2
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

  postgres:
    image: postgres:12
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: airflow
    ports:
      - "5433:5432"
